### ISSUE TITLE
about linux docker file

### ISSUE THREAD

**Issue by DannyGokey** [ryusatgat/ryugod#2]
Hey, nice project for online complier.
can i get a docker file from somewhere can run it with locally?

**Comment by ryusatgat** [comment]
> Hey, nice project for online complier. can i get a docker file from somewhere can run it with locally?

Sure, you can. try http://www.ryugod.com/ryugod_20221024.tar.gz

**Comment by neeraj26jan** [comment]
Hi mate. I need a dockerfile. Thanks a lot!
