### ISSUE TITLE
Hi i am trying to setup this to my server but could not connect to my terminal 

### ISSUE THREAD

**Issue by VikasCodeWizard** [ryusatgat/ryugod#3]
can you help? my email: vikasshukla5537@gmail.com

**Comment by ryusatgat** [comment]
Hello Vikas. saddly, I have no time to help you(I have a job for a living..). you can download docker image for the terminal to connect. (Docker must be installed your server, Install the docker image with REPOSITORY "ubuntu" and TAG "ryugod".
http://www.ryugod.com/ryugod_20221024.tar.gz
Thank you!
