### ISSUE TITLE
Can you send me your Dockerfile ?

### ISSUE THREAD

**Issue by axy1976** [ryusatgat/ryugod#4]
Hey ryu,

Your repo is lit.🔥
I have seen the closed issue and got the image zip file but instead of i want the dockerfile so it doesn't take so much time to build the image and wait for downloaded image file.

Thank you. 🙌🏼

**Comment by ryusatgat** [comment]
Hello axy1976, I am not a professional programmer(Just my fun hobby). so, I didn't know about dockerfile(not now) when I developed ryugod.
You can download Docker image at http://www.ryugod.com/ryugod_20221024.tar.gz
Ryugod is running on my home server. if you have download it, I'll remove it. Thank you!

**Comment by axy1976** [comment]
Hey Ryu, thank you for your response.

I have this docker image but you have so much in it and I want to work with limited compilers that's why I want to break down the docker image and regenerate image using dockerfile it might be in your root directory of this project named dockerfile without any extension.

If possible pls help me. Thank you. 🙌🏼

**Comment by axy1976** [comment]
Dockerfile created by me as follows

```
# Use Alpine Linux 3.14 as the base image
FROM alpine:3.14

# Install common development tools and libraries
RUN apk --update --no-cache add \
    build-base \
    vim \
    gcc \
    g++ \
    make \
    cmake \
    autoconf \
    automake \
    libtool \
    curl \
    wget \
    git \
    python3 \
    py3-pip \
    py3-numpy \ 
    boost-dev

# Create a new user named "cjr" with the specified UID and add to the "users" group
RUN adduser -D -u 1000 cjr

# Set a working directory
WORKDIR /home/cjr

# Switch to the "cjr" user
USER cjr

# Define the entry point for the image (this can be overridden in derived images)
CMD ["/bin/sh"]
```
