### ISSUE TITLE
DoKev 언어를 추가해주실 수 있나요?

### ISSUE THREAD

**Issue by BackGwa** [ryusatgat/ryugod#5]
### [DoKev](https://github.com/BackGwa/DoKev)는 쉽게 배울 수 있는 한글 프로그래밍 언어입니다.
현재 안정 된 버전은 C# 버전의 DoKev7이며, 이를 RyuGod에 추가해주실 수 있으신가요?

DoKev는 한글로 작성한 코드를 파이썬으로 변환 후 실행합니다.
이때, config.ini 파일을 참조하여, 변환 할 코드 파일과 실행할 인터프리터를 설정할 수 있습니다.

Windows. Linux, macOS 등 다양한 환경을 지원하며, x86과 ARM 모두 지원합니다!

> config.ini에 입력되는 경로는 절대 경로가 아닌, 빌더가 위치한 상대 경로입니다.

---

- DoKev의 예제 코드는 아래와 같습니다.
```
("안녕, 세상아!")라고 말해줘
```

> C# 버전의 DoKev에 더 자세한 내용이 필요하다면, [공식 문서](https://backgwa.notion.site/backgwa/DoKev-46bc63939be74aa28d3247ed2ec8d415)를 참조하시면 됩니다!

---

> [!NOTE]
> 현재, 도깨비 언어는 코드를 개선하고, 크로스 플랫폼 호환성을 위해,  Kotlin으로 이주를 준비하고 있습니다.
> 그 이전에 개발되던, C++ 버전의 DoKev는 더 이상 사용되지 않으니, 참고하시길 바랍니다!

**Comment by ryusatgat** [comment]
안녕하세요, 언어를 추가하는 것은 어렵지 않으나 아래와 같은 내용이 추가되거나 개선되어야 할 것으로 보입니다.

1. 예약어에 대한 전체 목록 (구문 강조를 위함)
2. DoKev 명령어와 config.ini 가 무조건 동일한 위치에 있어야 함 --> 프로젝트를 만들 때 DoKev 명령어와 의존 라이브러리가 항상 같이 위치해야 하므로 여러 소스를 만들고 싶을 때 어려움
3. 컴파일 정상 처리나 비정상 처리일 경우 모두 0으로 리턴 됨 (컴파일 오류가 났을 때의 상황을 인지할 수 있어야 함)
4. 컴파일 오류에 대한 라인 정보가 없음 (복잡한 소스의 경우 라인이 없으면 오류 찾기가 어려움)
5. 실행 시 인자를 받지 않음 (config.ini 는 기본 설정으로 가져가되 인자로 설정을 오버라이드 할 수 있어야 함)
  예)  Runner -e . -o main.py main.dkv

이중에서 가장 절실한 것은 인자 입력과 비정상 처리입니다. Runner가 어디에 있든지 소스 위치에 상관없이 컴파일 될 수 있어야 합니다.

한글 언어를 만들어 주셔서 감사드리고 위의 기능이 개선된다면 바로 등록해 드리겠습니다.

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-05-08 (수) 11:39:36 (GMT+09:00)
Subject: [ryusatgat/ryugod] DoKev 언어를 추가해주실 수 있나요? (Issue #5)

DoKev는 쉽게 배울 수 있는 한글 프로그래밍 언어입니다.
현재 안정 된 버전은 C# 버전의 DoKev7이며, 이를 RyuGod에 추가해주실 수 있으신가요?
DoKev는 한글로 작성한 코드를 파이썬으로 변환 후 실행합니다.
이때, config.ini 파일을 참조하여, 변환 할 코드 파일과 실행할 인터프리터를 설정할 수 있습니다.
Windows. Linux, macOS 등 다양한 환경을 지원하며, x86과 ARM 모두 지원합니다!

config.ini에 입력되는 경로는 절대 경로가 아닌, 빌더가 위치한 상대 경로입니다.


DoKev의 예제 코드는 아래와 같습니다.

("안녕, 세상아!")라고 말해줘
C# 버전의 DoKev에 더 자세한 내용이 필요하다면, 공식 문서를 참조하시면 됩니다!

Note
현재, 도깨비 언어는 코드를 개선하고, 크로스 플랫폼 호환성을 위해, Kotlin으로 이주를 준비하고 있습니다.
그 이전에 개발되던, C++ 버전의 DoKev는 더 이상 사용되지 않으니, 참고하시길 바랍니다!

**Comment by BackGwa** [comment]
안녕하세요, 빠르게 이슈를 확인해주셔서 정말 감사드립니다.

사실 DoKev의 C++ 버전은 언급 된 모든 문제가 해결되어 있습니다.

<details>
<summary>해결 된 문제</summary>

- 컴파일러 인자
컴파일러에 특정 파일을 컴파일하게, 인자를 입력할 수 있습니다.

```sh
./dokev -c Example.dkv
```

- 디버거 추가
아래와 같이 소스코드에 오류가 발생하면, 그 부분을 가르킵니다.

![스크린샷 2024-05-07 030318](https://github.com/ryusatgat/ryugod/assets/64456214/d8db6865-b662-40ee-bd86-fbf87bfd652d)

</details>

하지만, C++ 버전은 당장 사용하기엔 일부 기능이 구현되어 있지 않으며,
사용자 환경에 따라, 컴파일에 오류가 발생하는 등, 안정성이 떨어집니다.

이로 인해, 개발을 중단학고, 코틀린으로 이주 작업을 진행하고 있습니다.
관심을 가져주셔서 정말로 감사드리고, 빠르게 이주 작업을 마치도록 하겠습니다.

감사합니다.

**Comment by ryusatgat** [comment]
DoKev 언어의 C# 버전이 아래에 추가되었습니다. 인자 처리와 정상/비정상 부분은 셸스크립트로 해결하였습니다.

https://www.ryugod.com/pages/ide/dokev

**Comment by BackGwa** [comment]
수고를 끼쳐드려서 정말 죄송합니다 ㅠㅠ 
더 좋은 언어로 뵙겠습니다!

정말로 감사드립니다!
