### ISSUE TITLE
Vulnerabilities -- Invite to chat

### ISSUE THREAD

**Issue by DaemonOnUnix** [ryusatgat/ryugod#6]
Hello,

A friend of mine wanted to oversee the security of ryugod because he wanted to deploy his own instance.

I guess I found some vulnerabilities in your deployment and misconfigurations in your Dockerfile...

Do you have a discord for us to chat a bit and send them to you ? It would be better to not have a public disclosure until fix.

Respectful regards,

-- 
DaemonOnUnix

**Comment by DaemonOnUnix** [comment]
Issue addressed, will close the issue.

-- 
DaemonOnUnix

**Comment by ryusatgat** [comment]
Thank you for your interest in the ryugod.com website. It was hastily created for personal purpose, so security was not a major consideration during development. As you may know, ryugod.com has numerous security vulnerabilities (although I am not an expert in Node.js or Docker, but I'm security specialist 😁). There is no Dockerfile for ryugod.com; instead, all files are bundled into a single image (I developed it without understanding the concept of Dockerfiles at the time).

If I find the time and regain interest in development, I plan to create Ryugod.com Version 2. At that point, I will take security into account and proceed carefully. This site is open for anonymous users to test code temporarily, so even if it gets hacked, there’s no need to worry excessively—it would only result in a brief site outage. Unfortunately, I don’t have any channels related to Discord or development; I work in the securities industry(not security). Thank you once again for taking an interest in this humble site!

You can download docker image at http://ryugod.com/ryugod_20221024.tar.gz
