### ISSUE TITLE
Docker file download link is not working

### ISSUE THREAD

**Issue by neeraj26jan** [ryusatgat/ryugod#7]
Hi mate, you did a nice job. I am very interested in downloading the Docker file but couldn't download it as the link is not working. Could you share the Docker file with me? Thanks!

**Comment by ryusatgat** [comment]
You can still download that docker image.

http://www.ryugod.com/ryugod_20221024.tar.gz

remember that the protocol is HTTP not HTTPS.

-----Original Message-----
From: "Niraj ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2024-06-12 (수) 22:04:38 (GMT+09:00)
Subject: [ryusatgat/ryugod] Docker file download link is not working (Issue #7)

Hi mate, you did a nice job. I am very interested in downloading the Docker file but couldn't download it as the link is not working. Could you share the Docker file with me? Thanks!
